### ISSUE TITLE
multiple graphs/property_paths on same class

### ISSUE THREAD

**Issue by MartinP7r** [iben12/laravel-statable#10]
Hi, I was wondering if it would be possible to apply more than one statemachine to the class? e.g. when you have two different state variables on the same model?  
It seems that right now, `getGraph` can only set for one graph that in turn is coupled to one `property_path`.

**Comment by MartinP7r** [comment]
I figured it makes more sense to ask this over at the sebdesign repo. So I opened this question as well: https://github.com/sebdesign/laravel-state-machine/issues/30

**Comment by iben12** [comment]
Hi @MartinP7r,
I've seen the discussion in the other repo and it's true that the state-machine itself has no restrictions on using multiple instances for the same (model) class.

Regarding the statable trait, my aim was to cover the most typical use-case with a very simple (opinionated) solution. I think your use-case is not typical, and the whole thing had to be re-thinked from the ground up to support it. And the result wouldn't be dead simple anymore.

So you are welcome to fork this repo and implement a solution that satisfies your needs, but I'm sorry to say, that I don't think I want to incorporate it into this trait. But who knows? ¯\_(ツ)_/¯ Maybe you come up with with a very nice and simple solution.

If you need some advice on how to start off with this, I can help.

**Comment by MartinP7r** [comment]
That's fair enough. Thanks for the input!  
I'll have a look at how I might implement it.  

(In another issue @sebdesign implemented a feature for passing data when applying transitions. I've already started to implement this in a fork of your repo and would make a (different) pull request for it.)
