### ISSUE TITLE
Add a variation of saveBeforeTransition() for automatically persisting last_state in database?

### ISSUE THREAD

**Issue by leonelngande** [iben12/laravel-statable#20]
Hi again,

You created this trait to make it easier to work with the state machine, correct? :-)
A pain point I've been dealing with is having to manually save the model after successfully applying a transition.  That is so the updated `last_state` value is persisted in the database. 

What if this could equally happen in Statable@apply() method? A variation of Statable@saveBeforeTransition() that takes care of this use case.

What's your thought on this please? An implementation that won't break the current saveBeforeTransition() functionality.

Thanks 🙏.

**Comment by iben12** [comment]
We could add a similar switch like the `saveModelAfterTransition`, but I'm not sure.

A common use-case would be something like:
```php
$model = Post::find(1);

try {
  $model->apply('publish');
} catch (\Exception $e) {
  // handle failure
}
$model->published_at = new Carbon();
$model->save();
``` 
I mean usually you do something else on the model than just apply a transition, but it's just my opinion.

On the other hand an easier and more generic solution would be to add an after hook (much like the `StateHistoryManager`) in your own project that just saves the model on transition event.

Convince me! ;)

**Comment by leonelngande** [comment]
LOL!

Yea you're right, others likely perform other actions after applying the transition, like setting published_at in your example.

Yea can definitely add an after hook, but for the life of me I've not been able to get callbacks working!! For two days now lol.

Just like with the hook approach, am currently listening for the POST_TRANSITION event in EventServiceProvider.
```
SMEvents::POST_TRANSITION => [
    AfterTransition::class,
]
```
then proceed with persisting the updated last_state in the event listener execute method (AfterTransition@execute()).
```
<?php

namespace App\Listeners;

use App\AirtimeRequest;
use Sebdesign\SM\Event\TransitionEvent;

class AfterTransition
{
    public function __construct()
    {
        //
    }

    public function handle(TransitionEvent $event)
    {
        /** @var AirtimeRequest $airtimeRequest */
        $airtimeRequest = $event->getStateMachine()->getObject();

        // Persist the model so the updated `last_state` from above operation is saved to database.
        $airtimeRequest->save();

        // ...
    }
}
```
