### ISSUE TITLE
Custom StateHistory model or connection

### ISSUE THREAD

**Issue by vpratfr** [iben12/laravel-statable#25]
We are using the package in a multi-tenant app. The connection for the models is determined dynamically and thus the StateHistory model needs to be set on the proper connection.

I see two options:

1. allow configuring a custom model for the StateHistory model used (to provide a custom class which will use the right connection). 
2. have a configuration option to set the connection to be used by the models of the package. That setting would then be used by the StateHistory model

I would suggest 1., this is the way most packages allow such customization.

Would you be able to do that? Do you want a PR?

**Comment by iben12** [comment]
Hi @vpratfr,

Option 1 seems OK for me as well. I would appreciate a PR on this. 

Cheers

**Comment by vpratfr** [comment]
Done. Let me know if it needs additional stuff. I decided to use a second configuration file in order to keep the state machine description separate.
