### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by willhatchVista** [iben12/laravel-statable#29]
Hi,
I'm enjoying using this package, and as I test a migration to PHP 8 I'm getting a warning from composer that this package isn't compatible. My tests using the trait have no complaints with the shift FYI.

>  - iben12/laravel-statable[v1.4, ..., v1.4.1] require php ^7.2 -> your php version (8.0; overridden via config.platform, same as actual) does not satisfy that requirement.

**Comment by iben12** [comment]
Hi,
Good call, but this just blew up right in my hand, up to the point it's fresh news today that Travis CI dropped free tier for OSS projects. I feel like [Hal fixing a light bulb (from Malcolm in the Middle S03E06 - Health Scare)](https://www.youtube.com/watch?v=AbSehcT19u0).

Anyway, seems like upstream project [sebdesign/laravel-state-machine](https://github.com/sebdesign/laravel-state-machine) also supports PHP up to `^7.2.5` only, which would break your installation even if my package would allow PHP 8.

So let's keep this open, I will switch the CI in the meantime and hope for an update in sebdesign/laravel-state-machine.

For the time being the only workaround I can think of is `composer install --ignore-platform-reqs`.

**Comment by willhatchVista** [comment]
Thanks for the follow up. That's terrible news, I really appreciated how they supported the little projects. 

I came to a similar conclusion after digging deeper into the issue. At first composer just warned of a small handful of minor packages, but later was listing over a dozen. 

Seems that we need to give some time to library developers before revisiting.

**Comment by iben12** [comment]
Fixed in #30
