### ISSUE TITLE
Your recommendations to store comments

### ISSUE THREAD

**Issue by fbollon** [iben12/laravel-statable#37]
Hello,
I would like to test this package but I don't see an option for comments during transitions.
What is your opinion/recommendation if I want to allow users to leave a comment during a transition and to be able to find this comment in the history

Thanks for your help

**Comment by iben12** [comment]
Hi,
I think I would extend the `state_history` table with a `comment` field via new [migration](https://github.com/iben12/laravel-statable/blob/432bf420e0e8082ae4d2acc1c866b4428a944af2/database/migrations/create_state_history_table.php.stub#L15) and then override the `addHistoryLine` method of the trait ([original here](https://github.com/iben12/laravel-statable/blob/432bf420e0e8082ae4d2acc1c866b4428a944af2/src/Statable.php#L30)) in the model class with the addition of something like
```
$transitionData['comment'] = $this->getComment();
```
Of course you have to implement the way to get the input string in the `getComment` method of the model class as well.

How do you like that?

**Comment by fbollon** [comment]
Sounds good 
I'll give it a try

Thanks
