### ISSUE TITLE
Update for sebdesign/laravel-state-machine v2

### ISSUE THREAD

**Issue by simensen** [iben12/laravel-statable#9]
I'd like to give this package a try but it does not support the newest stable versions of sebdesign/laravel-state-machine. It was recently updated to support Laravel 6 and bumped its versions to 2.x.

See [its changelog](https://github.com/sebdesign/laravel-state-machine/blob/master/CHANGELOG.md#v200---2019-09-02) for more details.

Unclear to me if this would be as easy as relaxing the version constraints for sebdesign/laravel-state-machine or if it would require more work.

**Comment by iben12** [comment]
Thanks for bringing this into attention.

I don't see if I'll have some time for checking this very soon, but will try to find some slot for it.

In the meantime if someone can try to run the tests with Laravel 6 and sebdesign/laravel-state-machine 2.x I would happily accept a PR on this issue.

**Comment by iben12** [comment]
I have updated the dependencies and tests are OK. Testbench 4.x is compatible with Laravel 6.

Also dropped PHP 7.0 and 7.1 support.

Could you try to install the `dev-master` to see if it works as expected?

**Comment by simensen** [comment]
@iben12 it looks like it is working fine for me, but will admit I don't know in which ways it could fail. :) Thanks for the quick turnaround!

**Comment by horaceho** [comment]
Version conflict during installation:

$ composer require iben12/laravel-statable
Using version ^0.1.0 for iben12/laravel-statable
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: sebdesign/laravel-state-machine[v1.x-dev, v2.0.2].
    - Can only install one of: sebdesign/laravel-state-machine[v2.0.2, v1.x-dev].
    - Can only install one of: sebdesign/laravel-state-machine[v1.x-dev, v2.0.2].
    - iben12/laravel-statable v0.1 requires sebdesign/laravel-state-machine ^1.3 -> satisfiable by sebdesign/laravel-state-machine[v1.x-dev].
    - Installation request for iben12/laravel-statable ^0.1.0 -> satisfiable by iben12/laravel-statable[v0.1].
    - Installation request for sebdesign/laravel-state-machine (locked at v2.0.2, required as ^2.0) -> satisfiable by sebdesign/laravel-state-machine[v2.0.2].

**Comment by simensen** [comment]
@horaceho indeed, you would need to do the following to get it to work w/ the new version constraints:

```
composer require iben12/laravel-statable:dev-master
```

or even maybe...

```
composer require iben12/laravel-statable:@dev
```

You can see from the Composer output that it is selecting only stable versions (for which none exist as yet w/ this fix) of laravel-statable:

> Using version ^0.1.0 for iben12/laravel-statable

**Comment by iben12** [comment]
@horaceo As it seems to work now, I will release v1.0 that is compatible with sebdesign/laravel-state-machine 2.x and Laravel 6.

In the meantime you can use what @simensen suggested: install the `dev-master`.

**Comment by simensen** [comment]
I upgraded to v1.0 and it worked just fine. :) Thank you so much for the quick turnaround, @iben12!!! I'll close this issue for now. :)
